### ISSUE TITLE
Integrate Nextflow commands into visualization module

### ISSUE THREAD

**Issue by anwarMZ** [cidgoh/VIRUS-MVP#74]
Currently, `data_parser.py` is converting VCF to GVF which is then parsed for visualization. Lets move towards integrating `nextflow` commands now which will require following updates 

1. Allow user to upload `.vcf` or `.fasta` or `.tsv` file.
2. Need a check to confirm the file type based on which this `nextflow` command will be structured

`nextflow run nf-ncov-voc/main.nf  -profile < conda | singularity | docker > --prefix < unique_user_id > --mode user --input_type < vcf | tsv | fasta > --userfile < user_uploaded_file > --outdir < output directory where files will be generated >`

**Comment by ivansg44** [comment]
@anwarMZ Close this?
